### ISSUE TITLE
Slides don't fill window

### ISSUE THREAD

**Issue by aminimalanimal** [elpete/eaglejs-template#1]
It seems that there's some CSS that didn't make the transfer from the [Eagle.js demo](https://zulko.github.io/eaglejs-demo/#/your-first-slideshow) to this template. The slides don't take up the full `height` or `width` of the screen.

<img width="1818" alt="screen shot 2018-01-23 at 10 59 54 am" src="https://user-images.githubusercontent.com/3333654/35289418-ee318e86-002c-11e8-82e3-be82e402c9e3.png">

Subsequent slides end up sliding in under the others because of these missing styles.

**Comment by aminimalanimal** [comment]
This might be an issue with eagle.js itself: https://github.com/Zulko/eagle.js/issues/36

**Comment by elpete** [comment]
Yup, looks like you got the help you needed in the main repo.  Thanks.
